# Generated by Django 3.2.9 on 2021-11-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=300)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='userfeed.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='userfeed.user')),
            ],
        ),
        migrations.CreateModel(
            name='TopicFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeed.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeed.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeed.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeed.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeed.user'),
        ),
    ]
